package com.gallary.gallaryV1.model;

import java.time.LocalDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "Uploaded file data")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "files")
public class FileDetails {

    @Schema(example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Schema(example = "filename.jpg")
    private String fileName;

    @Schema(example = "D:/uploads/filename.jpg")
    private String filePath;

    @Schema(example = "for cloudinary delete and retrieve")
    private String publicId;

    private String resourceType;

    @Schema(example = "File details generated by NLP Model")
    @Column(length = 2000)
    private String description;

    @Schema(description = "Tags to categorize files")
    @ElementCollection
    @CollectionTable(
        name = "file_tags",
        joinColumns = @JoinColumn(name = "file_id")
    )
    @Column(name = "tag")
    private List<String> tags;

    @Schema(description = "Uploader of the file")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Schema(description = "Time of upload of file")
    private LocalDateTime uploadTime;
}
